from pathlib import Path
import nbformat as nbf

OUTPUT_NOTEBOOK = Path('08_DDPM_2D_Geometric_Patterns.ipynb')

CELL_SPECS = [{'type': 'markdown',
  'source': '# DDPM — From Gaussian Noise to 2D Geometric Patterns\n'
            '\n'
            '### A visual laboratory for conditional diffusion on synthetic point clouds\n'
            '\n'
            'Notebook 07 established the mathematical machinery of DDPMs: forward diffusion, the noise-prediction '
            'objective, and the reverse Gaussian process.\n'
            '\n'
            'This notebook moves that machinery into a visual 2D laboratory.\n'
            '\n'
            'The central question is:\n'
            '\n'
            '> **Can a diffusion model learn difficult geometric point distributions and generate those distributions '
            'starting from pure Gaussian noise?**\n'
            '\n'
            'We work with points\n'
            '\n'
            '$$\n'
            'x_0 =\n'
            '\\begin{bmatrix}\n'
            'x\\\\\n'
            'y\n'
            '\\end{bmatrix}\n'
            '\\in \\mathbb{R}^2,\n'
            '$$\n'
            '\n'
            'and the forward diffusion equation from Notebook 07:\n'
            '\n'
            '$$\n'
            'x_t = \\sqrt{\\bar{\\alpha}_t}x_0 +\n'
            '\\sqrt{1-\\bar{\\alpha}_t}\\epsilon,\n'
            '\\qquad\n'
            '\\epsilon \\sim \\mathcal{N}(0,I_2).\n'
            '$$\n'
            '\n'
            'The conditional network predicts\n'
            '\n'
            '$$\n'
            '\\epsilon_\\theta(x_t,t,y),\n'
            '$$\n'
            '\n'
            'where $y$ is the geometric pattern class.\n'
            '\n'
            'The notebook revolves around one visual idea:\n'
            '\n'
            '```text\n'
            'Gaussian Noise\n'
            '      |\n'
            '      v\n'
            '  Reverse Diffusion\n'
            '      |\n'
            '      v\n'
            '  Rough Structure\n'
            '      |\n'
            '      v\n'
            'Recognizable Geometry\n'
            '      |\n'
            '      v\n'
            ' Clean 2D Pattern\n'
            '```\n'
            '\n'
            'The final experiment makes this trajectory visible with animated GIFs.\n'},
 {'type': 'code',
  'source': '# Core imports and reproducibility\n'
            '\n'
            'from pathlib import Path\n'
            'import math\n'
            'import numpy as np\n'
            'import matplotlib.pyplot as plt\n'
            '\n'
            'import torch\n'
            'import torch.nn as nn\n'
            'import torch.nn.functional as F\n'
            'from torch.utils.data import Dataset, DataLoader\n'
            '\n'
            'from sklearn.datasets import make_moons\n'
            'from tqdm.auto import tqdm\n'
            'from matplotlib.animation import FuncAnimation, PillowWriter\n'
            'from IPython.display import display, Image as IPyImage\n'
            '\n'
            'torch.manual_seed(42)\n'
            'np.random.seed(42)\n'
            '\n'
            'DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")\n'
            'ARTIFACT_DIR = Path("artifacts")\n'
            'ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)\n'
            '\n'
            'print("Device:", DEVICE)\n'},
 {'type': 'markdown',
  'source': '## 01 — Pattern Laboratory\n'
            '\n'
            'We build exactly seven classes, ordered from easy to difficult.\n'
            '\n'
            'The important point is that these are **2D probability distributions**, not sequences and not images.\n'
            '\n'
            'Each generator returns points in $\\mathbb{R}^2$. We later normalize all classes together so that one '
            'coordinate system can be used for training and visualization.\n'},
 {'type': 'code',
  'source': '# Pattern names and shared data configuration\n'
            '\n'
            'PATTERN_NAMES = [\n'
            '    "Pattern 0 — Gaussian Blob",\n'
            '    "Pattern 1 — Ring",\n'
            '    "Pattern 2 — Two Moons",\n'
            '    "Pattern 3 — Nested Rings",\n'
            '    "Pattern 4 — Spiral",\n'
            '    "Pattern 5 — Double Spiral",\n'
            '    "Pattern 6 — GPT-Inspired Knot",\n'
            ']\n'
            '\n'
            'NUM_CLASSES = len(PATTERN_NAMES)\n'
            'POINTS_PER_CLASS = 4500\n'
            '\n'
            'print("Number of classes:", NUM_CLASSES)\n'
            'for name in PATTERN_NAMES:\n'
            '    print(name)\n'},
 {'type': 'markdown',
  'source': '### Pattern 0 — Gaussian Blob\n'
            '\n'
            'The baseline is a compact Gaussian distribution,\n'
            '\n'
            '$$\n'
            'x \\sim \\mathcal{N}(\\mu,\\sigma^2I).\n'
            '$$\n'
            '\n'
            'There is no thin manifold to discover. The task is simply to learn where probability mass is '
            'concentrated.\n'},
 {'type': 'code',
  'source': 'def make_gaussian_blob(n, rng, sigma=0.38):\n'
            '    mean = np.array([0.0, 0.0])\n'
            '    points = rng.normal(loc=mean, scale=sigma, size=(n, 2))\n'
            '    return points.astype(np.float32)\n'},
 {'type': 'markdown',
  'source': '### Pattern 1 — Ring\n'
            '\n'
            'A ring is a one-dimensional curve embedded in two dimensions:\n'
            '\n'
            '$$\n'
            'x = r\\cos\\theta,\n'
            '\\qquad\n'
            'y = r\\sin\\theta,\n'
            '$$\n'
            '\n'
            'with\n'
            '\n'
            '$$\n'
            'r = r_0 + \\delta,\n'
            '\\qquad\n'
            '\\delta \\sim \\mathcal{N}(0,\\sigma_r^2).\n'
            '$$\n'
            '\n'
            'This introduces a low-dimensional manifold inside $\\mathbb{R}^2$.\n'},
 {'type': 'code',
  'source': 'def make_ring(n, rng, radius=1.15, radial_noise=0.055):\n'
            '    theta = rng.uniform(0.0, 2.0 * np.pi, size=n)\n'
            '    r = radius + rng.normal(0.0, radial_noise, size=n)\n'
            '\n'
            '    x = r * np.cos(theta)\n'
            '    y = r * np.sin(theta)\n'
            '\n'
            '    return np.column_stack([x, y]).astype(np.float32)\n'},
 {'type': 'markdown',
  'source': '### Pattern 2 — Two Moons\n'
            '\n'
            'The two-moons distribution contains two curved, interleaving manifolds.\n'
            '\n'
            'Compared with a ring, it is harder because there is no single radial coordinate that describes the whole '
            'distribution. The two branches also have non-convex local geometry.\n'},
 {'type': 'code',
  'source': 'def make_two_moons(n, rng, noise=0.055):\n'
            '    # sklearn gives a reproducible implementation of the classic two-moons geometry.\n'
            '    seed = int(rng.integers(0, 2**31 - 1))\n'
            '    points, _ = make_moons(n_samples=n, noise=noise, random_state=seed)\n'
            '\n'
            '    points = points.astype(np.float32)\n'
            '    points -= points.mean(axis=0, keepdims=True)\n'
            '    points *= 0.95\n'
            '\n'
            '    # A small rotation gives the class a slightly different visual orientation.\n'
            '    angle = 0.16\n'
            '    rot = np.array(\n'
            '        [[np.cos(angle), -np.sin(angle)],\n'
            '         [np.sin(angle),  np.cos(angle)]],\n'
            '        dtype=np.float32,\n'
            '    )\n'
            '    points = points @ rot.T\n'
            '    return points.astype(np.float32)\n'},
 {'type': 'markdown',
  'source': '### Pattern 3 — Nested Rings\n'
            '\n'
            'Now multiple manifolds share the same center:\n'
            '\n'
            '$$\n'
            'r \\in \\{0.50, 1.00, 1.50\\}.\n'
            '$$\n'
            '\n'
            'The model must distinguish multiple spatial scales even though the global symmetry is similar across the '
            'rings.\n'},
 {'type': 'code',
  'source': 'def make_nested_rings(n, rng, radii=(0.50, 1.00, 1.50), radial_noise=0.045):\n'
            '    ring_ids = rng.integers(0, len(radii), size=n)\n'
            '    theta = rng.uniform(0.0, 2.0 * np.pi, size=n)\n'
            '    r = np.asarray(radii, dtype=np.float32)[ring_ids]\n'
            '    r = r + rng.normal(0.0, radial_noise, size=n)\n'
            '\n'
            '    x = r * np.cos(theta)\n'
            '    y = r * np.sin(theta)\n'
            '    return np.column_stack([x, y]).astype(np.float32)\n'},
 {'type': 'markdown',
  'source': '### Pattern 4 — Spiral\n'
            '\n'
            'An Archimedean spiral follows\n'
            '\n'
            '$$\n'
            'r = a+b\\theta,\n'
            '$$\n'
            '\n'
            'then\n'
            '\n'
            '$$\n'
            'x=r\\cos\\theta,\n'
            '\\qquad\n'
            'y=r\\sin\\theta.\n'
            '$$\n'
            '\n'
            'The radius changes continuously along the curve, so the model must preserve long-range nonlinear '
            'structure rather than a simple global symmetry.\n'},
 {'type': 'code',
  'source': 'def make_spiral(n, rng, turns=2.55, noise=0.035):\n'
            '    theta = rng.uniform(0.0, turns * 2.0 * np.pi, size=n)\n'
            '    r = 0.08 + 0.115 * theta\n'
            '\n'
            '    x = r * np.cos(theta)\n'
            '    y = r * np.sin(theta)\n'
            '\n'
            '    points = np.column_stack([x, y])\n'
            '    points += rng.normal(0.0, noise, size=points.shape)\n'
            '\n'
            '    points -= points.mean(axis=0, keepdims=True)\n'
            '    points /= np.max(np.abs(points)) / 1.55\n'
            '    return points.astype(np.float32)\n'},
 {'type': 'markdown',
  'source': '### Pattern 5 — Intertwined Double Spiral / Pinwheel\n'
            '\n'
            'We use two phase-shifted Archimedean spirals,\n'
            '\n'
            '$$\n'
            'r=a+b\\theta,\n'
            '$$\n'
            '\n'
            'with one branch shifted by approximately $\\pi$.\n'
            '\n'
            'This creates multiple intertwined trajectories with rotational structure.\n'},
 {'type': 'code',
  'source': 'def make_double_spiral(n, rng, turns=2.75, noise=0.032):\n'
            '    n0 = n // 2\n'
            '    n1 = n - n0\n'
            '\n'
            '    theta0 = rng.uniform(0.0, turns * 2.0 * np.pi, size=n0)\n'
            '    theta1 = rng.uniform(0.0, turns * 2.0 * np.pi, size=n1)\n'
            '\n'
            '    r0 = 0.08 + 0.105 * theta0\n'
            '    r1 = 0.08 + 0.105 * theta1\n'
            '\n'
            '    phase0 = theta0\n'
            '    phase1 = theta1 + np.pi\n'
            '\n'
            '    p0 = np.column_stack([r0 * np.cos(phase0), r0 * np.sin(phase0)])\n'
            '    p1 = np.column_stack([r1 * np.cos(phase1), r1 * np.sin(phase1)])\n'
            '\n'
            '    points = np.concatenate([p0, p1], axis=0)\n'
            '    points += rng.normal(0.0, noise, size=points.shape)\n'
            '\n'
            '    points -= points.mean(axis=0, keepdims=True)\n'
            '    points /= np.max(np.abs(points)) / 1.60\n'
            '    return points.astype(np.float32)\n'},
 {'type': 'markdown',
  'source': '### Pattern 6 — GPT-Inspired Geometric Knot\n'
            '\n'
            'This class is procedurally generated. No external logo image is downloaded.\n'
            '\n'
            'We construct several rounded, elongated loops arranged around a common center. Each loop is '
            'parameterized, rotated, translated, and slightly perturbed. Their overlap produces an interlocking '
            'knot-like geometry inspired by the multi-loop form associated with the GPT/OpenAI visual language.\n'
            '\n'
            'The goal is not exact logo reproduction. The goal is a mathematically generated **complex interlocking '
            'distribution** with:\n'
            '\n'
            '- multiple local curves,\n'
            '- repeated rotational structure,\n'
            '- intersections,\n'
            '- and global geometric consistency.\n'},
 {'type': 'code',
  'source': 'def _rounded_loop(u):\n'
            '    # A smooth, slightly non-circular loop with two harmonic components.\n'
            '    radial = 0.42 + 0.12 * np.cos(2.0 * u) + 0.035 * np.cos(4.0 * u)\n'
            '    x = radial * np.cos(u)\n'
            '    y = 1.28 * radial * np.sin(u)\n'
            '    return np.column_stack([x, y])\n'
            '\n'
            '\n'
            'def _rotate(points, angle):\n'
            '    rot = np.array(\n'
            '        [[np.cos(angle), -np.sin(angle)],\n'
            '         [np.sin(angle),  np.cos(angle)]],\n'
            '        dtype=np.float32,\n'
            '    )\n'
            '    return points @ rot.T\n'
            '\n'
            '\n'
            'def make_gpt_inspired_knot(\n'
            '    n,\n'
            '    rng,\n'
            '    loop_count=6,\n'
            '    deformation=0.04,\n'
            '    rotation_jitter=0.05,\n'
            '    coordinate_noise=0.018,\n'
            '):\n'
            '    counts = np.full(loop_count, n // loop_count, dtype=int)\n'
            '    counts[: n % loop_count] += 1\n'
            '\n'
            '    pieces = []\n'
            '\n'
            '    for i, count in enumerate(counts):\n'
            '        u = rng.uniform(0.0, 2.0 * np.pi, size=count)\n'
            '\n'
            '        loop = _rounded_loop(u).astype(np.float32)\n'
            '\n'
            '        phase = 2.0 * np.pi * i / loop_count\n'
            '        local_rotation = phase + np.pi / 2.0\n'
            '        local_rotation += rng.normal(0.0, rotation_jitter)\n'
            '\n'
            '        # Place the loops around a circular backbone.\n'
            '        center = np.array(\n'
            '            [0.53 * np.cos(phase), 0.53 * np.sin(phase)],\n'
            '            dtype=np.float32,\n'
            '        )\n'
            '\n'
            '        loop = _rotate(loop, local_rotation)\n'
            '        loop *= 1.0 + rng.normal(0.0, deformation)\n'
            '        loop += center\n'
            '\n'
            '        pieces.append(loop)\n'
            '\n'
            '    points = np.concatenate(pieces, axis=0)\n'
            '\n'
            '    # A mild global non-linear deformation makes the distribution\n'
            '    # more realistic while preserving the core knot geometry.\n'
            '    x = points[:, 0].copy()\n'
            '    y = points[:, 1].copy()\n'
            '\n'
            '    x_new = x + deformation * 0.18 * np.sin(2.5 * y)\n'
            '    y_new = y + deformation * 0.18 * np.sin(2.5 * x)\n'
            '\n'
            '    points = np.column_stack([x_new, y_new])\n'
            '    points += rng.normal(0.0, coordinate_noise, size=points.shape)\n'
            '\n'
            '    # Random global rotation keeps the class rotationally structured\n'
            '    # without making every generated cloud identical in orientation.\n'
            '    global_angle = rng.uniform(-0.10, 0.10)\n'
            '    points = _rotate(points.astype(np.float32), global_angle)\n'
            '\n'
            '    points -= points.mean(axis=0, keepdims=True)\n'
            '    points /= np.max(np.abs(points)) / 1.75\n'
            '\n'
            '    return points.astype(np.float32)\n'},
 {'type': 'markdown',
  'source': '### Build all seven distributions\n'
            '\n'
            'We keep the classes balanced and use fixed random seeds so the notebook is reproducible.\n'
            '\n'
            'After generating the raw point clouds, we normalize **all classes together**. This keeps their relative '
            'geometry comparable.\n'},
 {'type': 'code',
  'source': 'def build_all_patterns(points_per_class=POINTS_PER_CLASS, seed=42):\n'
            '    generators = [\n'
            '        make_gaussian_blob,\n'
            '        make_ring,\n'
            '        make_two_moons,\n'
            '        make_nested_rings,\n'
            '        make_spiral,\n'
            '        make_double_spiral,\n'
            '        make_gpt_inspired_knot,\n'
            '    ]\n'
            '\n'
            '    all_points = []\n'
            '    all_labels = []\n'
            '\n'
            '    for class_id, generator in enumerate(generators):\n'
            '        class_rng = np.random.default_rng(seed + 1000 * class_id)\n'
            '        points = generator(points_per_class, class_rng)\n'
            '\n'
            '        all_points.append(points)\n'
            '        all_labels.append(\n'
            '            np.full(points_per_class, class_id, dtype=np.int64)\n'
            '        )\n'
            '\n'
            '    points = np.concatenate(all_points, axis=0)\n'
            '    labels = np.concatenate(all_labels, axis=0)\n'
            '\n'
            '    # Normalize the complete dataset to approximately [-1.8, 1.8]^2.\n'
            '    scale = 1.8 / np.max(np.abs(points))\n'
            '    points = points * scale\n'
            '\n'
            '    return points.astype(np.float32), labels.astype(np.int64)\n'
            '\n'
            '\n'
            'all_points, all_labels = build_all_patterns()\n'
            '\n'
            'print("All points:", all_points.shape)\n'
            'print("Coordinate minimum:", all_points.min(axis=0))\n'
            'print("Coordinate maximum:", all_points.max(axis=0))\n'},
 {'type': 'markdown',
  'source': '## 02 — Visualize the Entire Dataset\n'
            '\n'
            'The first figure is the most important sanity check for the dataset itself.\n'
            '\n'
            'Every panel uses equal x/y scaling, because geometry is being learned in Euclidean 2D space.\n'},
 {'type': 'code',
  'source': 'fig, axes = plt.subplots(2, 4, figsize=(16, 8))\n'
            'axes = axes.ravel()\n'
            '\n'
            'for class_id, name in enumerate(PATTERN_NAMES):\n'
            '    mask = all_labels == class_id\n'
            '    axes[class_id].scatter(\n'
            '        all_points[mask, 0],\n'
            '        all_points[mask, 1],\n'
            '        s=5,\n'
            '        alpha=0.45,\n'
            '    )\n'
            '    axes[class_id].set_title(name)\n'
            '    axes[class_id].set_aspect("equal")\n'
            '    axes[class_id].set_xlim(-2.0, 2.0)\n'
            '    axes[class_id].set_ylim(-2.0, 2.0)\n'
            '\n'
            'axes[-1].axis("off")\n'
            'fig.suptitle("Seven 2D Geometric Distributions")\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': 'A second view samples a smaller number of points from each class. This makes local structure easier to '
            'inspect.\n'},
 {'type': 'code',
  'source': 'fig, axes = plt.subplots(2, 4, figsize=(16, 8))\n'
            'axes = axes.ravel()\n'
            'rng = np.random.default_rng(123)\n'
            '\n'
            'for class_id, name in enumerate(PATTERN_NAMES):\n'
            '    mask = np.flatnonzero(all_labels == class_id)\n'
            '    chosen = rng.choice(mask, size=min(700, len(mask)), replace=False)\n'
            '\n'
            '    axes[class_id].scatter(\n'
            '        all_points[chosen, 0],\n'
            '        all_points[chosen, 1],\n'
            '        s=8,\n'
            '        alpha=0.55,\n'
            '    )\n'
            '    axes[class_id].set_title(f"{name}\\nrandom subset")\n'
            '    axes[class_id].set_aspect("equal")\n'
            '    axes[class_id].set_xlim(-2.0, 2.0)\n'
            '    axes[class_id].set_ylim(-2.0, 2.0)\n'
            '\n'
            'axes[-1].axis("off")\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': '## 03 — Geometry Before Diffusion\n'
            '\n'
            'Before training anything, identify what makes the classes increasingly difficult:\n'
            '\n'
            '| Pattern | Geometric structure |\n'
            '|---|---|\n'
            '| Gaussian Blob | simple unimodal density |\n'
            '| Ring | one-dimensional manifold in $\\mathbb{R}^2$ |\n'
            '| Two Moons | interleaved, non-convex manifolds |\n'
            '| Nested Rings | multiple spatial scales |\n'
            '| Spiral | strong nonlinear curvature |\n'
            '| Double Spiral | multiple intertwined trajectories |\n'
            '| GPT-Inspired Knot | several local curves plus global interlocking structure |\n'
            '\n'
            'The diffusion model is **not** asked to memorize a coordinate table. It is learning a conditional '
            'probability distribution\n'
            '\n'
            '$$\n'
            'p_\\theta(x\\mid y)\n'
            '$$\n'
            '\n'
            'over 2D space.\n'},
 {'type': 'markdown',
  'source': '## 04 — Train / Validation / Test\n'
            '\n'
            'We split every class independently so all three subsets remain balanced.\n'
            '\n'
            'Each dataset item returns\n'
            '\n'
            '```python\n'
            'x0\n'
            'label\n'
            '```\n'
            '\n'
            'with\n'
            '\n'
            '```python\n'
            'x0.shape == [2]\n'
            '```\n'
            '\n'
            'and an integer class label.\n'},
 {'type': 'code',
  'source': 'def balanced_train_val_test_split(points, labels, train_ratio=0.70, val_ratio=0.15, seed=42):\n'
            '    rng = np.random.default_rng(seed)\n'
            '\n'
            '    train_indices = []\n'
            '    val_indices = []\n'
            '    test_indices = []\n'
            '\n'
            '    for class_id in range(NUM_CLASSES):\n'
            '        indices = np.flatnonzero(labels == class_id)\n'
            '        rng.shuffle(indices)\n'
            '\n'
            '        n = len(indices)\n'
            '        n_train = int(train_ratio * n)\n'
            '        n_val = int(val_ratio * n)\n'
            '\n'
            '        train_indices.append(indices[:n_train])\n'
            '        val_indices.append(indices[n_train:n_train + n_val])\n'
            '        test_indices.append(indices[n_train + n_val:])\n'
            '\n'
            '    return (\n'
            '        np.concatenate(train_indices),\n'
            '        np.concatenate(val_indices),\n'
            '        np.concatenate(test_indices),\n'
            '    )\n'
            '\n'
            '\n'
            'train_idx, val_idx, test_idx = balanced_train_val_test_split(\n'
            '    all_points,\n'
            '    all_labels,\n'
            ')\n'
            '\n'
            'train_points, train_labels = all_points[train_idx], all_labels[train_idx]\n'
            'val_points, val_labels = all_points[val_idx], all_labels[val_idx]\n'
            'test_points, test_labels = all_points[test_idx], all_labels[test_idx]\n'
            '\n'
            'print("Train:", train_points.shape)\n'
            'print("Validation:", val_points.shape)\n'
            'print("Test:", test_points.shape)\n'},
 {'type': 'code',
  'source': 'class Synthetic2DPatternDataset(Dataset):\n'
            '    def __init__(self, points, labels):\n'
            '        self.points = torch.as_tensor(points, dtype=torch.float32)\n'
            '        self.labels = torch.as_tensor(labels, dtype=torch.long)\n'
            '\n'
            '    def __len__(self):\n'
            '        return len(self.points)\n'
            '\n'
            '    def __getitem__(self, index):\n'
            '        return self.points[index], self.labels[index]\n'
            '\n'
            '\n'
            'train_dataset = Synthetic2DPatternDataset(train_points, train_labels)\n'
            'val_dataset = Synthetic2DPatternDataset(val_points, val_labels)\n'
            'test_dataset = Synthetic2DPatternDataset(test_points, test_labels)\n'
            '\n'
            'BATCH_SIZE = 512 if DEVICE.type == "cuda" else 256\n'
            '\n'
            'train_loader = DataLoader(\n'
            '    train_dataset,\n'
            '    batch_size=BATCH_SIZE,\n'
            '    shuffle=True,\n'
            '    drop_last=True,\n'
            ')\n'
            'val_loader = DataLoader(\n'
            '    val_dataset,\n'
            '    batch_size=BATCH_SIZE,\n'
            '    shuffle=False,\n'
            ')\n'
            'test_loader = DataLoader(\n'
            '    test_dataset,\n'
            '    batch_size=BATCH_SIZE,\n'
            '    shuffle=False,\n'
            ')\n'
            '\n'
            'example_x, example_y = train_dataset[0]\n'
            '\n'
            'print("Single point shape:", example_x.shape)\n'
            'print("Single label shape:", example_y.shape)\n'
            'print("Coordinate range:", train_points.min(), "to", train_points.max())\n'
            'print("Number of classes:", NUM_CLASSES)\n'
            'print("Device:", DEVICE)\n'},
 {'type': 'markdown',
  'source': '## 05 — Forward Diffusion in 2D\n'
            '\n'
            'Notebook 07 already derived the forward process. Here we reuse exactly the same closed-form equation:\n'
            '\n'
            '$$\n'
            'x_t =\n'
            '\\sqrt{\\bar\\alpha_t}x_0\n'
            '+\n'
            '\\sqrt{1-\\bar\\alpha_t}\\epsilon,\n'
            '\\qquad\n'
            '\\epsilon\\sim\\mathcal{N}(0,I_2).\n'
            '$$\n'
            '\n'
            'The only new idea is visual: because $x_0$ is now a 2D coordinate, we can watch geometry disappear.\n'},
 {'type': 'code',
  'source': '# DDPM schedule\n'
            '\n'
            'T = 300\n'
            'beta_start = 1e-4\n'
            'beta_end = 0.02\n'
            '\n'
            'betas = torch.linspace(beta_start, beta_end, T, device=DEVICE)\n'
            'alphas = 1.0 - betas\n'
            'alpha_bars = torch.cumprod(alphas, dim=0)\n'
            '\n'
            'sqrt_alpha_bars = torch.sqrt(alpha_bars)\n'
            'sqrt_one_minus_alpha_bars = torch.sqrt(1.0 - alpha_bars)\n'
            '\n'
            'posterior_variance = torch.zeros_like(betas)\n'
            'posterior_variance[1:] = (\n'
            '    betas[1:] * (1.0 - alpha_bars[:-1]) / (1.0 - alpha_bars[1:])\n'
            ')\n'
            '\n'
            'diffusion = {\n'
            '    "T": T,\n'
            '    "betas": betas,\n'
            '    "alphas": alphas,\n'
            '    "alpha_bars": alpha_bars,\n'
            '    "sqrt_alpha_bars": sqrt_alpha_bars,\n'
            '    "sqrt_one_minus_alpha_bars": sqrt_one_minus_alpha_bars,\n'
            '    "posterior_variance": posterior_variance,\n'
            '}\n'
            '\n'
            'print("T =", T)\n'
            'print("alpha_bar[0]  =", alpha_bars[0].item())\n'
            'print("alpha_bar[-1] =", alpha_bars[-1].item())\n'},
 {'type': 'code',
  'source': 'def extract(schedule_tensor, t, x_shape):\n'
            '    values = schedule_tensor[t]\n'
            '    return values.view(-1, *([1] * (len(x_shape) - 1)))\n'
            '\n'
            '\n'
            'def q_sample(x0, t, schedule, noise=None):\n'
            '    if noise is None:\n'
            '        noise = torch.randn_like(x0)\n'
            '\n'
            '    sqrt_ab = extract(\n'
            '        schedule["sqrt_alpha_bars"],\n'
            '        t,\n'
            '        x0.shape,\n'
            '    )\n'
            '    sqrt_1mab = extract(\n'
            '        schedule["sqrt_one_minus_alpha_bars"],\n'
            '        t,\n'
            '        x0.shape,\n'
            '    )\n'
            '\n'
            '    xt = sqrt_ab * x0 + sqrt_1mab * noise\n'
            '    return xt\n'},
 {'type': 'markdown',
  'source': 'Take a single ring and use the **same underlying clean points** at several timesteps.\n'
            '\n'
            'This makes the progression\n'
            '\n'
            '```text\n'
            'Clean Geometry\n'
            '      ↓\n'
            'Geometry + Noise\n'
            '      ↓\n'
            'Weak Structure\n'
            '      ↓\n'
            'Almost Gaussian\n'
            '      ↓\n'
            'Pure Noise\n'
            '```\n'
            '\n'
            'visually explicit.\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def plot_forward_diffusion_example(\n'
            '    class_id=1,\n'
            '    timesteps=(0, 50, 100, 200, T - 1),\n'
            '    n_points=900,\n'
            '):\n'
            '    points = test_points[test_labels == class_id]\n'
            '    points = points[:n_points]\n'
            '\n'
            '    x0 = torch.as_tensor(points, dtype=torch.float32, device=DEVICE)\n'
            '    noise = torch.randn_like(x0)\n'
            '\n'
            '    fig, axes = plt.subplots(1, len(timesteps), figsize=(18, 3.5))\n'
            '\n'
            '    for ax, timestep in zip(axes, timesteps):\n'
            '        t = torch.full(\n'
            '            (len(x0),),\n'
            '            timestep,\n'
            '            dtype=torch.long,\n'
            '            device=DEVICE,\n'
            '        )\n'
            '        xt = q_sample(x0, t, diffusion, noise=noise)\n'
            '\n'
            '        ax.scatter(\n'
            '            xt[:, 0].cpu(),\n'
            '            xt[:, 1].cpu(),\n'
            '            s=7,\n'
            '            alpha=0.5,\n'
            '        )\n'
            '        ax.set_title(f"t = {timestep}")\n'
            '        ax.set_aspect("equal")\n'
            '        ax.set_xlim(-2.0, 2.0)\n'
            '        ax.set_ylim(-2.0, 2.0)\n'
            '\n'
            '    fig.suptitle("Forward Diffusion of the Ring")\n'
            '    plt.tight_layout()\n'
            '    plt.show()\n'
            '\n'
            '\n'
            'plot_forward_diffusion_example()\n'},
 {'type': 'markdown',
  'source': '## 06 — Signal-to-Noise Intuition\n'
            '\n'
            'Two scalar curves summarize the closed-form forward process:\n'
            '\n'
            '$$\n'
            '\\sqrt{\\bar\\alpha_t}\n'
            '$$\n'
            '\n'
            'measures how strongly the original geometry remains, while\n'
            '\n'
            '$$\n'
            '\\sqrt{1-\\bar\\alpha_t}\n'
            '$$\n'
            '\n'
            'measures how strongly Gaussian noise contributes.\n'},
 {'type': 'code',
  'source': 'timesteps = np.arange(T)\n'
            '\n'
            'plt.figure(figsize=(9, 4.5))\n'
            'plt.plot(\n'
            '    timesteps,\n'
            '    sqrt_alpha_bars.cpu(),\n'
            '    label=r"$\\sqrt{\\bar{\\alpha}_t}$",\n'
            ')\n'
            'plt.plot(\n'
            '    timesteps,\n'
            '    sqrt_one_minus_alpha_bars.cpu(),\n'
            '    label=r"$\\sqrt{1-\\bar{\\alpha}_t}$",\n'
            ')\n'
            'plt.xlabel("Timestep t")\n'
            'plt.ylabel("Scale")\n'
            'plt.title("Signal and Noise Scales")\n'
            'plt.legend()\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def plot_noise_levels(class_id=2):\n'
            '    points = test_points[test_labels == class_id][:800]\n'
            '    x0 = torch.as_tensor(points, dtype=torch.float32, device=DEVICE)\n'
            '    noise = torch.randn_like(x0)\n'
            '\n'
            '    chosen_t = [0, 40, 100, 180, 260, T - 1]\n'
            '\n'
            '    fig, axes = plt.subplots(2, 3, figsize=(12, 8))\n'
            '    axes = axes.ravel()\n'
            '\n'
            '    for ax, timestep in zip(axes, chosen_t):\n'
            '        t = torch.full(\n'
            '            (len(x0),),\n'
            '            timestep,\n'
            '            dtype=torch.long,\n'
            '            device=DEVICE,\n'
            '        )\n'
            '        xt = q_sample(x0, t, diffusion, noise=noise)\n'
            '\n'
            '        ax.scatter(\n'
            '            xt[:, 0].cpu(),\n'
            '            xt[:, 1].cpu(),\n'
            '            s=7,\n'
            '            alpha=0.48,\n'
            '        )\n'
            '        ax.set_title(\n'
            '            f"t={timestep}\\n"\n'
            '            f"signal={sqrt_alpha_bars[timestep].item():.2f}, "\n'
            '            f"noise={sqrt_one_minus_alpha_bars[timestep].item():.2f}"\n'
            '        )\n'
            '        ax.set_aspect("equal")\n'
            '        ax.set_xlim(-2.0, 2.0)\n'
            '        ax.set_ylim(-2.0, 2.0)\n'
            '\n'
            '    plt.tight_layout()\n'
            '    plt.show()\n'
            '\n'
            '\n'
            'plot_noise_levels()\n'},
 {'type': 'markdown',
  'source': '## 07 — Conditional Diffusion Model\n'
            '\n'
            'The model receives three things:\n'
            '\n'
            '$$\n'
            'x_t\\in\\mathbb{R}^2,\n'
            '\\qquad\n'
            't,\n'
            '\\qquad\n'
            'y\\in\\{0,\\ldots,6\\}.\n'
            '$$\n'
            '\n'
            'It predicts\n'
            '\n'
            '$$\n'
            '\\epsilon_\\theta(x_t,t,y)\\in\\mathbb{R}^2.\n'
            '$$\n'
            '\n'
            'The architecture is deliberately small:\n'
            '\n'
            '```text\n'
            'x_t ───────────────┐\n'
            '                   │\n'
            'time embedding ────┼──> MLP ───> predicted noise\n'
            '                   │\n'
            'class embedding ──┘\n'
            '```\n'
            '\n'
            'The time embedding is sinusoidal, while the pattern label uses a trainable `nn.Embedding`.\n'},
 {'type': 'code',
  'source': 'class SinusoidalTimeEmbedding(nn.Module):\n'
            '    def __init__(self, dim):\n'
            '        super().__init__()\n'
            '        self.dim = dim\n'
            '\n'
            '    def forward(self, t):\n'
            '        half = self.dim // 2\n'
            '        if half == 1:\n'
            '            frequencies = torch.ones(\n'
            '                1,\n'
            '                device=t.device,\n'
            '                dtype=torch.float32,\n'
            '            )\n'
            '        else:\n'
            '            frequencies = torch.exp(\n'
            '                -math.log(10000.0)\n'
            '                * torch.arange(\n'
            '                    half,\n'
            '                    device=t.device,\n'
            '                    dtype=torch.float32,\n'
            '                )\n'
            '                / (half - 1)\n'
            '            )\n'
            '\n'
            '        angles = t.float().unsqueeze(1) * frequencies.unsqueeze(0)\n'
            '        embedding = torch.cat(\n'
            '            [torch.sin(angles), torch.cos(angles)],\n'
            '            dim=1,\n'
            '        )\n'
            '\n'
            '        if self.dim % 2 == 1:\n'
            '            embedding = F.pad(embedding, (0, 1))\n'
            '\n'
            '        return embedding\n'
            '\n'
            '\n'
            'class ConditionalDiffusionMLP(nn.Module):\n'
            '    def __init__(\n'
            '        self,\n'
            '        num_classes,\n'
            '        time_dim=32,\n'
            '        class_dim=16,\n'
            '        hidden_dim=128,\n'
            '    ):\n'
            '        super().__init__()\n'
            '\n'
            '        self.time_embedding = SinusoidalTimeEmbedding(time_dim)\n'
            '        self.class_embedding = nn.Embedding(num_classes, class_dim)\n'
            '\n'
            '        input_dim = 2 + time_dim + class_dim\n'
            '\n'
            '        self.network = nn.Sequential(\n'
            '            nn.Linear(input_dim, hidden_dim),\n'
            '            nn.SiLU(),\n'
            '            nn.Linear(hidden_dim, hidden_dim),\n'
            '            nn.SiLU(),\n'
            '            nn.Linear(hidden_dim, 2),\n'
            '        )\n'
            '\n'
            '    def forward(self, x_t, t, y):\n'
            '        time_features = self.time_embedding(t)\n'
            '        class_features = self.class_embedding(y)\n'
            '\n'
            '        features = torch.cat(\n'
            '            [x_t, time_features, class_features],\n'
            '            dim=1,\n'
            '        )\n'
            '\n'
            '        return self.network(features)\n'
            '\n'
            '\n'
            'model = ConditionalDiffusionMLP(\n'
            '    num_classes=NUM_CLASSES,\n'
            '    time_dim=32,\n'
            '    class_dim=16,\n'
            '    hidden_dim=128,\n'
            ').to(DEVICE)\n'
            '\n'
            'print(model)\n'
            'print("Parameters:", sum(p.numel() for p in model.parameters()))\n'},
 {'type': 'markdown',
  'source': '## 08 — DDPM Training\n'
            '\n'
            'The standard simplified DDPM objective is\n'
            '\n'
            '$$\n'
            '\\boxed{\n'
            'L_{\\mathrm{simple}}\n'
            '=\n'
            '\\mathbb{E}\n'
            '\\left[\n'
            '\\left\\|\n'
            '\\epsilon\n'
            '-\n'
            '\\epsilon_\\theta(x_t,t,y)\n'
            '\\right\\|^2\n'
            '\\right]\n'
            '}.\n'
            '$$\n'
            '\n'
            'The training loop is:\n'
            '\n'
            '```text\n'
            'sample x0\n'
            '   ↓\n'
            'sample class y\n'
            '   ↓\n'
            'sample timestep t\n'
            '   ↓\n'
            'sample Gaussian noise ε\n'
            '   ↓\n'
            'construct xt\n'
            '   ↓\n'
            'predict ε\n'
            '   ↓\n'
            'MSE(ε, ε̂)\n'
            '   ↓\n'
            'backpropagation\n'
            '```\n'
            '\n'
            'We train the same network across all seven classes.\n'},
 {'type': 'code',
  'source': 'def diffusion_loss(model, x0, labels, schedule):\n'
            '    batch_size = x0.shape[0]\n'
            '\n'
            '    t = torch.randint(\n'
            '        low=0,\n'
            '        high=schedule["T"],\n'
            '        size=(batch_size,),\n'
            '        device=x0.device,\n'
            '        dtype=torch.long,\n'
            '    )\n'
            '\n'
            '    noise = torch.randn_like(x0)\n'
            '    xt = q_sample(x0, t, schedule, noise=noise)\n'
            '\n'
            '    predicted_noise = model(xt, t, labels)\n'
            '    loss = F.mse_loss(predicted_noise, noise)\n'
            '\n'
            '    return loss\n'},
 {'type': 'code',
  'source': 'def run_epoch(model, loader, schedule, optimizer=None):\n'
            '    training = optimizer is not None\n'
            '    model.train(training)\n'
            '\n'
            '    total_loss = 0.0\n'
            '    total_count = 0\n'
            '\n'
            '    iterator = tqdm(\n'
            '        loader,\n'
            '        leave=False,\n'
            '        desc="train" if training else "val",\n'
            '    )\n'
            '\n'
            '    for x0, labels in iterator:\n'
            '        x0 = x0.to(DEVICE)\n'
            '        labels = labels.to(DEVICE)\n'
            '\n'
            '        if training:\n'
            '            optimizer.zero_grad(set_to_none=True)\n'
            '\n'
            '        loss = diffusion_loss(\n'
            '            model,\n'
            '            x0,\n'
            '            labels,\n'
            '            schedule,\n'
            '        )\n'
            '\n'
            '        if training:\n'
            '            loss.backward()\n'
            '            optimizer.step()\n'
            '\n'
            '        batch_size = len(x0)\n'
            '        total_loss += loss.item() * batch_size\n'
            '        total_count += batch_size\n'
            '\n'
            '    return total_loss / total_count\n'
            '\n'
            '\n'
            'EPOCHS = 30 if DEVICE.type == "cuda" else 15\n'
            'LEARNING_RATE = 2e-3\n'
            '\n'
            'optimizer = torch.optim.Adam(\n'
            '    model.parameters(),\n'
            '    lr=LEARNING_RATE,\n'
            ')\n'
            '\n'
            'best_val_loss = float("inf")\n'
            'history = {\n'
            '    "train": [],\n'
            '    "val": [],\n'
            '}\n'
            '\n'
            'checkpoint_path = ARTIFACT_DIR / "best_diffusion_2d.pt"\n'
            '\n'
            'for epoch in range(1, EPOCHS + 1):\n'
            '    train_loss = run_epoch(\n'
            '        model,\n'
            '        train_loader,\n'
            '        diffusion,\n'
            '        optimizer=optimizer,\n'
            '    )\n'
            '    val_loss = run_epoch(\n'
            '        model,\n'
            '        val_loader,\n'
            '        diffusion,\n'
            '        optimizer=None,\n'
            '    )\n'
            '\n'
            '    history["train"].append(train_loss)\n'
            '    history["val"].append(val_loss)\n'
            '\n'
            '    if val_loss < best_val_loss:\n'
            '        best_val_loss = val_loss\n'
            '        torch.save(model.state_dict(), checkpoint_path)\n'
            '\n'
            '    print(\n'
            '        f"Epoch {epoch:02d}/{EPOCHS} | "\n'
            '        f"train={train_loss:.6f} | "\n'
            '        f"val={val_loss:.6f}"\n'
            '    )\n'
            '\n'
            'print("Best checkpoint:", checkpoint_path)\n'},
 {'type': 'code',
  'source': 'model.load_state_dict(torch.load(checkpoint_path, map_location=DEVICE))\n'
            'model.eval()\n'
            '\n'
            'plt.figure(figsize=(8, 4.5))\n'
            'plt.plot(history["train"], label="Train")\n'
            'plt.plot(history["val"], label="Validation")\n'
            'plt.xlabel("Epoch")\n'
            'plt.ylabel("Noise-prediction MSE")\n'
            'plt.title("DDPM Training Curve")\n'
            'plt.legend()\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': '## 09 — First Test: Noise Prediction\n'
            '\n'
            'Before sampling from scratch, test the actual supervised target of the DDPM.\n'
            '\n'
            'For a known noisy point cloud we know the injected $\\epsilon$. The network produces $\\hat\\epsilon$.\n'
            '\n'
            'The question is therefore:\n'
            '\n'
            '$$\n'
            '(x_t,t,y)\\longrightarrow\\epsilon.\n'
            '$$\n'
            '\n'
            'This is the learned denoising signal that later drives reverse diffusion.\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def evaluate_noise_prediction(model, n_points=400, class_id=4, timestep=180):\n'
            '    class_points = test_points[test_labels == class_id]\n'
            '    points = class_points[:n_points]\n'
            '\n'
            '    x0 = torch.as_tensor(points, dtype=torch.float32, device=DEVICE)\n'
            '    labels = torch.full(\n'
            '        (len(x0),),\n'
            '        class_id,\n'
            '        dtype=torch.long,\n'
            '        device=DEVICE,\n'
            '    )\n'
            '    t = torch.full(\n'
            '        (len(x0),),\n'
            '        timestep,\n'
            '        dtype=torch.long,\n'
            '        device=DEVICE,\n'
            '    )\n'
            '\n'
            '    true_noise = torch.randn_like(x0)\n'
            '    xt = q_sample(x0, t, diffusion, noise=true_noise)\n'
            '    predicted_noise = model(xt, t, labels)\n'
            '\n'
            '    mse = F.mse_loss(predicted_noise, true_noise).item()\n'
            '\n'
            '    return x0, xt, true_noise, predicted_noise, mse\n'
            '\n'
            '\n'
            'x0_noise, xt_noise, true_eps, pred_eps, eps_mse = evaluate_noise_prediction(\n'
            '    model,\n'
            ')\n'
            '\n'
            'print(f"Noise prediction MSE: {eps_mse:.6f}")\n'},
 {'type': 'code',
  'source': '# A vector-style comparison of true injected noise and predicted noise.\n'
            '\n'
            'sample_count = 70\n'
            'base = xt_noise[:sample_count].cpu().numpy()\n'
            'true_vec = true_eps[:sample_count].cpu().numpy()\n'
            'pred_vec = pred_eps[:sample_count].cpu().numpy()\n'
            '\n'
            'fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n'
            '\n'
            'axes[0].scatter(base[:, 0], base[:, 1], s=10, alpha=0.55)\n'
            'axes[0].quiver(\n'
            '    base[:, 0],\n'
            '    base[:, 1],\n'
            '    true_vec[:, 0],\n'
            '    true_vec[:, 1],\n'
            '    angles="xy",\n'
            '    scale_units="xy",\n'
            '    scale=5,\n'
            '    alpha=0.65,\n'
            ')\n'
            'axes[0].set_title("True injected noise")\n'
            'axes[0].set_aspect("equal")\n'
            'axes[0].set_xlim(-2.0, 2.0)\n'
            'axes[0].set_ylim(-2.0, 2.0)\n'
            '\n'
            'axes[1].scatter(base[:, 0], base[:, 1], s=10, alpha=0.55)\n'
            'axes[1].quiver(\n'
            '    base[:, 0],\n'
            '    base[:, 1],\n'
            '    pred_vec[:, 0],\n'
            '    pred_vec[:, 1],\n'
            '    angles="xy",\n'
            '    scale_units="xy",\n'
            '    scale=5,\n'
            '    alpha=0.65,\n'
            ')\n'
            'axes[1].set_title("Predicted noise")\n'
            'axes[1].set_aspect("equal")\n'
            'axes[1].set_xlim(-2.0, 2.0)\n'
            'axes[1].set_ylim(-2.0, 2.0)\n'
            '\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': '## 10 — Estimate $x_0$\n'
            '\n'
            'Because the model predicts noise, we can algebraically invert the forward equation:\n'
            '\n'
            '$$\n'
            '\\boxed{\n'
            '\\hat{x}_0 =\n'
            '\\frac{\n'
            'x_t\n'
            '-\n'
            '\\sqrt{1-\\bar\\alpha_t}\\,\n'
            '\\epsilon_\\theta(x_t,t,y)\n'
            '}{\n'
            '\\sqrt{\\bar\\alpha_t}\n'
            '}\n'
            '}.\n'
            '$$\n'
            '\n'
            'This is useful because it gives us a direct visual answer to:\n'
            '\n'
            '> What clean geometry does the model believe is hidden inside this noisy observation?\n'},
 {'type': 'code',
  'source': 'def predict_x0_from_noise(x_t, t, predicted_noise, schedule):\n'
            '    sqrt_ab = extract(\n'
            '        schedule["sqrt_alpha_bars"],\n'
            '        t,\n'
            '        x_t.shape,\n'
            '    )\n'
            '    sqrt_1mab = extract(\n'
            '        schedule["sqrt_one_minus_alpha_bars"],\n'
            '        t,\n'
            '        x_t.shape,\n'
            '    )\n'
            '\n'
            '    return (\n'
            '        x_t - sqrt_1mab * predicted_noise\n'
            '    ) / sqrt_ab\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def plot_x0_estimates(\n'
            '    timestep=180,\n'
            '    points_per_class=450,\n'
            '):\n'
            '    fig, axes = plt.subplots(\n'
            '        NUM_CLASSES,\n'
            '        3,\n'
            '        figsize=(11, 3.0 * NUM_CLASSES),\n'
            '    )\n'
            '\n'
            '    for class_id in range(NUM_CLASSES):\n'
            '        class_points = test_points[test_labels == class_id]\n'
            '        points = class_points[:points_per_class]\n'
            '\n'
            '        x0 = torch.as_tensor(\n'
            '            points,\n'
            '            dtype=torch.float32,\n'
            '            device=DEVICE,\n'
            '        )\n'
            '        labels = torch.full(\n'
            '            (len(x0),),\n'
            '            class_id,\n'
            '            dtype=torch.long,\n'
            '            device=DEVICE,\n'
            '        )\n'
            '        t = torch.full(\n'
            '            (len(x0),),\n'
            '            timestep,\n'
            '            dtype=torch.long,\n'
            '            device=DEVICE,\n'
            '        )\n'
            '\n'
            '        noise = torch.randn_like(x0)\n'
            '        xt = q_sample(\n'
            '            x0,\n'
            '            t,\n'
            '            diffusion,\n'
            '            noise=noise,\n'
            '        )\n'
            '        eps_hat = model(xt, t, labels)\n'
            '        x0_hat = predict_x0_from_noise(\n'
            '            xt,\n'
            '            t,\n'
            '            eps_hat,\n'
            '            diffusion,\n'
            '        )\n'
            '\n'
            '        clouds = [\n'
            '            x0.detach().cpu().numpy(),\n'
            '            xt.detach().cpu().numpy(),\n'
            '            x0_hat.detach().cpu().numpy(),\n'
            '        ]\n'
            '        titles = [\n'
            '            "Ground truth",\n'
            '            f"Noisy x_t (t={timestep})",\n'
            '            "Predicted x₀",\n'
            '        ]\n'
            '\n'
            '        for col in range(3):\n'
            '            axes[class_id, col].scatter(\n'
            '                clouds[col][:, 0],\n'
            '                clouds[col][:, 1],\n'
            '                s=6,\n'
            '                alpha=0.5,\n'
            '            )\n'
            '            axes[class_id, col].set_aspect("equal")\n'
            '            axes[class_id, col].set_xlim(-2.0, 2.0)\n'
            '            axes[class_id, col].set_ylim(-2.0, 2.0)\n'
            '\n'
            '            if class_id == 0:\n'
            '                axes[class_id, col].set_title(titles[col])\n'
            '\n'
            '        axes[class_id, 0].set_ylabel(\n'
            '            PATTERN_NAMES[class_id],\n'
            '            rotation=0,\n'
            '            labelpad=75,\n'
            '            va="center",\n'
            '        )\n'
            '\n'
            '    fig.suptitle("Estimating Clean Geometry from a Noisy Observation")\n'
            '    plt.tight_layout()\n'
            '    plt.show()\n'
            '\n'
            '\n'
            'plot_x0_estimates()\n'},
 {'type': 'markdown',
  'source': '## 11 — Reverse Diffusion Step\n'
            '\n'
            'The DDPM reverse mean from Notebook 07 is\n'
            '\n'
            '$$\n'
            '\\mu_\\theta(x_t,t,y)\n'
            '=\n'
            '\\frac{1}{\\sqrt{\\alpha_t}}\n'
            '\\left(\n'
            'x_t\n'
            '-\n'
            '\\frac{\\beta_t}\n'
            '{\\sqrt{1-\\bar\\alpha_t}}\n'
            '\\epsilon_\\theta(x_t,t,y)\n'
            '\\right).\n'
            '$$\n'
            '\n'
            'The posterior variance is\n'
            '\n'
            '$$\n'
            '\\tilde\\beta_t\n'
            '=\n'
            '\\beta_t\n'
            '\\frac{1-\\bar\\alpha_{t-1}}\n'
            '{1-\\bar\\alpha_t}.\n'
            '$$\n'
            '\n'
            'For $t>0$,\n'
            '\n'
            '$$\n'
            'x_{t-1}\n'
            '=\n'
            '\\mu_\\theta\n'
            '+\n'
            '\\sqrt{\\tilde\\beta_t}\\,z,\n'
            '\\qquad\n'
            'z\\sim\\mathcal{N}(0,I).\n'
            '$$\n'
            '\n'
            'We implement the step directly rather than using a diffusion library.\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def posterior_mean(x_t, t, predicted_noise, schedule):\n'
            '    beta_t = extract(\n'
            '        schedule["betas"],\n'
            '        t,\n'
            '        x_t.shape,\n'
            '    )\n'
            '    alpha_t = extract(\n'
            '        schedule["alphas"],\n'
            '        t,\n'
            '        x_t.shape,\n'
            '    )\n'
            '    sqrt_one_minus_ab = extract(\n'
            '        schedule["sqrt_one_minus_alpha_bars"],\n'
            '        t,\n'
            '        x_t.shape,\n'
            '    )\n'
            '\n'
            '    return (\n'
            '        1.0 / torch.sqrt(alpha_t)\n'
            '    ) * (\n'
            '        x_t\n'
            '        - (beta_t / sqrt_one_minus_ab) * predicted_noise\n'
            '    )\n'
            '\n'
            '\n'
            '@torch.no_grad()\n'
            'def p_sample_step(model, x_t, t, labels, schedule):\n'
            '    predicted_noise = model(x_t, t, labels)\n'
            '\n'
            '    mean = posterior_mean(\n'
            '        x_t,\n'
            '        t,\n'
            '        predicted_noise,\n'
            '        schedule,\n'
            '    )\n'
            '\n'
            '    variance = extract(\n'
            '        schedule["posterior_variance"],\n'
            '        t,\n'
            '        x_t.shape,\n'
            '    )\n'
            '\n'
            '    noise = torch.randn_like(x_t)\n'
            '\n'
            '    return mean + torch.sqrt(\n'
            '        torch.clamp(variance, min=0.0)\n'
            '    ) * noise\n'},
 {'type': 'markdown',
  'source': 'The sampler starts from\n'
            '\n'
            '$$\n'
            'x_{T-1}\\sim\\mathcal{N}(0,I_2)\n'
            '$$\n'
            '\n'
            'and repeatedly applies the learned reverse step.\n'
            '\n'
            'The `trajectory` returned by `sample` stores every reverse timestep so that the process can be animated '
            'later.\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def sample(\n'
            '    model,\n'
            '    schedule,\n'
            '    labels,\n'
            '    initial_noise=None,\n'
            '):\n'
            '    model.eval()\n'
            '\n'
            '    if initial_noise is None:\n'
            '        x = torch.randn(\n'
            '            len(labels),\n'
            '            2,\n'
            '            device=DEVICE,\n'
            '        )\n'
            '    else:\n'
            '        x = initial_noise.to(DEVICE).clone()\n'
            '\n'
            '    trajectory = [\n'
            '        (schedule["T"] - 1, x.detach().cpu().clone())\n'
            '    ]\n'
            '\n'
            '    for timestep in reversed(range(1, schedule["T"])):\n'
            '        t = torch.full(\n'
            '            (len(labels),),\n'
            '            timestep,\n'
            '            dtype=torch.long,\n'
            '            device=DEVICE,\n'
            '        )\n'
            '\n'
            '        x = p_sample_step(\n'
            '            model,\n'
            '            x,\n'
            '            t,\n'
            '            labels,\n'
            '            schedule,\n'
            '        )\n'
            '\n'
            '        trajectory.append(\n'
            '            (timestep - 1, x.detach().cpu().clone())\n'
            '        )\n'
            '\n'
            '    return x, trajectory\n'},
 {'type': 'markdown',
  'source': '## 12 — THE MAIN EXPERIMENT\n'
            '\n'
            'Now we generate all seven classes from fresh Gaussian noise.\n'
            '\n'
            'For each class:\n'
            '\n'
            '1. draw $x_{T-1}\\sim\\mathcal{N}(0,I)$,\n'
            '2. fix the desired class label $y$,\n'
            '3. repeatedly predict noise,\n'
            '4. move one reverse step,\n'
            '5. save the entire trajectory.\n'
            '\n'
            'The expected visual progression is:\n'
            '\n'
            '```text\n'
            'Gaussian Noise\n'
            '       ↓\n'
            'reverse steps\n'
            '       ↓\n'
            'rough geometry\n'
            '       ↓\n'
            'recognizable geometry\n'
            '       ↓\n'
            'final pattern\n'
            '```\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def generate_main_experiment(\n'
            '    points_per_class=800,\n'
            '):\n'
            '    generated = {}\n'
            '    trajectories = {}\n'
            '\n'
            '    for class_id in range(NUM_CLASSES):\n'
            '        labels = torch.full(\n'
            '            (points_per_class,),\n'
            '            class_id,\n'
            '            dtype=torch.long,\n'
            '            device=DEVICE,\n'
            '        )\n'
            '\n'
            '        final_points, trajectory = sample(\n'
            '            model,\n'
            '            diffusion,\n'
            '            labels,\n'
            '        )\n'
            '\n'
            '        generated[class_id] = final_points.cpu()\n'
            '        trajectories[class_id] = trajectory\n'
            '\n'
            '        print(\n'
            '            f"{PATTERN_NAMES[class_id]}: "\n'
            '            f"{final_points.shape}"\n'
            '        )\n'
            '\n'
            '    return generated, trajectories\n'
            '\n'
            '\n'
            'generated_by_class, trajectories_by_class = generate_main_experiment()\n'},
 {'type': 'code',
  'source': 'fig, axes = plt.subplots(2, 4, figsize=(16, 8))\n'
            'axes = axes.ravel()\n'
            '\n'
            'for class_id, name in enumerate(PATTERN_NAMES):\n'
            '    generated = generated_by_class[class_id].numpy()\n'
            '\n'
            '    axes[class_id].scatter(\n'
            '        generated[:, 0],\n'
            '        generated[:, 1],\n'
            '        s=6,\n'
            '        alpha=0.5,\n'
            '    )\n'
            '    axes[class_id].set_title(f"Generated — {name}")\n'
            '    axes[class_id].set_aspect("equal")\n'
            '    axes[class_id].set_xlim(-2.0, 2.0)\n'
            '    axes[class_id].set_ylim(-2.0, 2.0)\n'
            '\n'
            'axes[-1].axis("off")\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': '## 13 — Reverse Diffusion GIFs\n'
            '\n'
            'The animation uses the actual saved reverse trajectory.\n'
            '\n'
            'The axis limits are kept fixed for every frame so the geometry does not appear to move because of '
            'rescaling.\n'},
 {'type': 'code',
  'source': 'def make_reverse_gif(\n'
            '    trajectory,\n'
            '    class_name,\n'
            '    save_path,\n'
            '    frame_stride=5,\n'
            '    point_size=8,\n'
            '):\n'
            '    selected = trajectory[::frame_stride]\n'
            '\n'
            '    if selected[-1][0] != trajectory[-1][0]:\n'
            '        selected.append(trajectory[-1])\n'
            '\n'
            '    fig, ax = plt.subplots(figsize=(5.5, 5.5))\n'
            '\n'
            '    first_t, first_points = selected[0]\n'
            '    scatter = ax.scatter(\n'
            '        first_points[:, 0],\n'
            '        first_points[:, 1],\n'
            '        s=point_size,\n'
            '        alpha=0.55,\n'
            '    )\n'
            '\n'
            '    ax.set_xlim(-2.0, 2.0)\n'
            '    ax.set_ylim(-2.0, 2.0)\n'
            '    ax.set_aspect("equal")\n'
            '    ax.set_xlabel("x")\n'
            '    ax.set_ylabel("y")\n'
            '\n'
            '    def update(frame_index):\n'
            '        timestep, points = selected[frame_index]\n'
            '        scatter.set_offsets(points.numpy())\n'
            '        ax.set_title(\n'
            '            f"Reverse Diffusion — t = {timestep}\\n{class_name}"\n'
            '        )\n'
            '        return (scatter,)\n'
            '\n'
            '    animation = FuncAnimation(\n'
            '        fig,\n'
            '        update,\n'
            '        frames=len(selected),\n'
            '        interval=90,\n'
            '        blit=True,\n'
            '        repeat=False,\n'
            '    )\n'
            '\n'
            '    animation.save(\n'
            '        save_path,\n'
            '        writer=PillowWriter(fps=12),\n'
            '    )\n'
            '    plt.close(fig)\n'
            '\n'
            '    return save_path\n'},
 {'type': 'code',
  'source': 'gif_paths = []\n'
            '\n'
            'for class_id, name in enumerate(PATTERN_NAMES):\n'
            '    filename_map = {\n'
            '        0: "pattern_00_blob.gif",\n'
            '        1: "pattern_01_ring.gif",\n'
            '        2: "pattern_02_moons.gif",\n'
            '        3: "pattern_03_nested_rings.gif",\n'
            '        4: "pattern_04_spiral.gif",\n'
            '        5: "pattern_05_double_spiral.gif",\n'
            '        6: "pattern_06_gpt_knot.gif",\n'
            '    }\n'
            '\n'
            '    path = ARTIFACT_DIR / filename_map[class_id]\n'
            '\n'
            '    make_reverse_gif(\n'
            '        trajectories_by_class[class_id],\n'
            '        name,\n'
            '        path,\n'
            '        frame_stride=5,\n'
            '        point_size=8,\n'
            '    )\n'
            '\n'
            '    gif_paths.append(path)\n'
            '    print(path)\n'},
 {'type': 'markdown', 'source': '### Display the seven generated GIFs\n'},
 {'type': 'code',
  'source': 'for path in gif_paths:\n    print(path.name)\n    display(IPyImage(filename=str(path)))\n'},
 {'type': 'markdown',
  'source': '## 14 — Combined Reverse-Diffusion GIF\n'
            '\n'
            'Now use the same initial Gaussian noise for all seven conditions.\n'
            '\n'
            'The only thing that changes between panels is the class embedding.\n'},
 {'type': 'code',
  'source': 'def make_combined_reverse_gif(\n'
            '    model,\n'
            '    schedule,\n'
            '    save_path,\n'
            '    points_per_class=400,\n'
            '    frame_stride=5,\n'
            '    seed=1234,\n'
            '):\n'
            '    generator = torch.Generator(device=DEVICE)\n'
            '    generator.manual_seed(seed)\n'
            '\n'
            '    shared_noise = torch.randn(\n'
            '        points_per_class,\n'
            '        2,\n'
            '        generator=generator,\n'
            '        device=DEVICE,\n'
            '    )\n'
            '\n'
            '    x = shared_noise.repeat(NUM_CLASSES, 1)\n'
            '\n'
            '    labels = torch.arange(\n'
            '        NUM_CLASSES,\n'
            '        device=DEVICE,\n'
            '        dtype=torch.long,\n'
            '    ).repeat_interleave(points_per_class)\n'
            '\n'
            '    trajectory = [\n'
            '        (\n'
            '            schedule["T"] - 1,\n'
            '            x.detach()\n'
            '            .view(NUM_CLASSES, points_per_class, 2)\n'
            '            .cpu()\n'
            '            .clone(),\n'
            '        )\n'
            '    ]\n'
            '\n'
            '    for timestep in reversed(range(1, schedule["T"])):\n'
            '        t = torch.full(\n'
            '            (len(labels),),\n'
            '            timestep,\n'
            '            dtype=torch.long,\n'
            '            device=DEVICE,\n'
            '        )\n'
            '\n'
            '        x = p_sample_step(\n'
            '            model,\n'
            '            x,\n'
            '            t,\n'
            '            labels,\n'
            '            schedule,\n'
            '        )\n'
            '\n'
            '        trajectory.append(\n'
            '            (\n'
            '                timestep - 1,\n'
            '                x.detach()\n'
            '                .view(NUM_CLASSES, points_per_class, 2)\n'
            '                .cpu()\n'
            '                .clone(),\n'
            '            )\n'
            '        )\n'
            '\n'
            '    selected = trajectory[::frame_stride]\n'
            '    if selected[-1][0] != trajectory[-1][0]:\n'
            '        selected.append(trajectory[-1])\n'
            '\n'
            '    fig, axes = plt.subplots(2, 4, figsize=(13, 7))\n'
            '    axes = axes.ravel()\n'
            '\n'
            '    scatters = []\n'
            '\n'
            '    for class_id in range(NUM_CLASSES):\n'
            '        points0 = selected[0][1][class_id].numpy()\n'
            '        scatter = axes[class_id].scatter(\n'
            '            points0[:, 0],\n'
            '            points0[:, 1],\n'
            '            s=7,\n'
            '            alpha=0.5,\n'
            '        )\n'
            '        scatters.append(scatter)\n'
            '\n'
            '        axes[class_id].set_title(PATTERN_NAMES[class_id])\n'
            '        axes[class_id].set_aspect("equal")\n'
            '        axes[class_id].set_xlim(-2.0, 2.0)\n'
            '        axes[class_id].set_ylim(-2.0, 2.0)\n'
            '\n'
            '    axes[-1].axis("off")\n'
            '\n'
            '    def update(frame_index):\n'
            '        timestep, frame_points = selected[frame_index]\n'
            '\n'
            '        for class_id, scatter in enumerate(scatters):\n'
            '            scatter.set_offsets(\n'
            '                frame_points[class_id].numpy()\n'
            '            )\n'
            '\n'
            '        fig.suptitle(\n'
            '            f"All Conditions from the Same Gaussian Noise — t = {timestep}"\n'
            '        )\n'
            '        return tuple(scatters)\n'
            '\n'
            '    animation = FuncAnimation(\n'
            '        fig,\n'
            '        update,\n'
            '        frames=len(selected),\n'
            '        interval=90,\n'
            '        blit=False,\n'
            '        repeat=False,\n'
            '    )\n'
            '\n'
            '    animation.save(\n'
            '        save_path,\n'
            '        writer=PillowWriter(fps=12),\n'
            '    )\n'
            '    plt.close(fig)\n'
            '\n'
            '    return save_path\n'
            '\n'
            '\n'
            'combined_gif_path = ARTIFACT_DIR / "all_patterns_reverse_diffusion.gif"\n'
            '\n'
            'make_combined_reverse_gif(\n'
            '    model,\n'
            '    diffusion,\n'
            '    combined_gif_path,\n'
            ')\n'
            '\n'
            'print(combined_gif_path)\n'
            'display(IPyImage(filename=str(combined_gif_path)))\n'},
 {'type': 'markdown',
  'source': '## 15 — Static Reverse Trajectory\n'
            '\n'
            'The GIF is intuitive, but a static figure is useful for careful mathematical inspection.\n'
            '\n'
            'For one difficult class we show selected reverse timesteps:\n'
            '\n'
            '$$\n'
            't=T-1,\\;0.8T,\\;0.6T,\\;0.4T,\\;0.2T,\\;0.\n'
            '$$\n'},
 {'type': 'code',
  'source': 'def trajectory_to_dict(trajectory):\n'
            '    return {int(t): points for t, points in trajectory}\n'
            '\n'
            '\n'
            'class_id = 6\n'
            'trajectory_dict = trajectory_to_dict(\n'
            '    trajectories_by_class[class_id]\n'
            ')\n'
            '\n'
            'selected_t = [\n'
            '    T - 1,\n'
            '    int(0.8 * (T - 1)),\n'
            '    int(0.6 * (T - 1)),\n'
            '    int(0.4 * (T - 1)),\n'
            '    int(0.2 * (T - 1)),\n'
            '    0,\n'
            ']\n'
            '\n'
            'fig, axes = plt.subplots(2, 3, figsize=(12, 8))\n'
            'axes = axes.ravel()\n'
            '\n'
            'for ax, timestep in zip(axes, selected_t):\n'
            '    points = trajectory_dict[timestep].numpy()\n'
            '\n'
            '    ax.scatter(\n'
            '        points[:, 0],\n'
            '        points[:, 1],\n'
            '        s=7,\n'
            '        alpha=0.52,\n'
            '    )\n'
            '    ax.set_title(f"t = {timestep}")\n'
            '    ax.set_aspect("equal")\n'
            '    ax.set_xlim(-2.0, 2.0)\n'
            '    ax.set_ylim(-2.0, 2.0)\n'
            '\n'
            'fig.suptitle("Reverse Diffusion — GPT-Inspired Knot")\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': '## 16 — Easy → Hard Comparison\n'
            '\n'
            'Each row shows:\n'
            '\n'
            '```text\n'
            'Noise\n'
            'Intermediate\n'
            'Final\n'
            'Ground Truth\n'
            '```\n'
            '\n'
            'The goal is not to declare a universal difficulty ranking. Instead, inspect how long visible structure '
            'remains ambiguous for each learned distribution.\n'},
 {'type': 'code',
  'source': 'def find_nearest_timestep(trajectory, target_t):\n'
            '    return min(\n'
            '        trajectory,\n'
            '        key=lambda pair: abs(pair[0] - target_t),\n'
            '    )\n'
            '\n'
            '\n'
            'comparison_t = [\n'
            '    T - 1,\n'
            '    int(0.55 * (T - 1)),\n'
            ']\n'
            '\n'
            'fig, axes = plt.subplots(\n'
            '    NUM_CLASSES,\n'
            '    4,\n'
            '    figsize=(13, 3.0 * NUM_CLASSES),\n'
            ')\n'
            '\n'
            'for class_id in range(NUM_CLASSES):\n'
            '    noise_t, noise_points = find_nearest_timestep(\n'
            '        trajectories_by_class[class_id],\n'
            '        comparison_t[0],\n'
            '    )\n'
            '    mid_t, mid_points = find_nearest_timestep(\n'
            '        trajectories_by_class[class_id],\n'
            '        comparison_t[1],\n'
            '    )\n'
            '\n'
            '    final_points = generated_by_class[class_id].numpy()\n'
            '    truth_points = test_points[test_labels == class_id][:800]\n'
            '\n'
            '    columns = [\n'
            '        ("Noise", noise_points.numpy()),\n'
            '        (f"Intermediate\\nt={mid_t}", mid_points.numpy()),\n'
            '        ("Final", final_points.numpy()),\n'
            '        ("Ground Truth", truth_points),\n'
            '    ]\n'
            '\n'
            '    for col, (title, points) in enumerate(columns):\n'
            '        axes[class_id, col].scatter(\n'
            '            points[:, 0],\n'
            '            points[:, 1],\n'
            '            s=6,\n'
            '            alpha=0.5,\n'
            '        )\n'
            '        axes[class_id, col].set_aspect("equal")\n'
            '        axes[class_id, col].set_xlim(-2.0, 2.0)\n'
            '        axes[class_id, col].set_ylim(-2.0, 2.0)\n'
            '\n'
            '        if class_id == 0:\n'
            '            axes[class_id, col].set_title(title)\n'
            '\n'
            '    axes[class_id, 0].set_ylabel(\n'
            '        PATTERN_NAMES[class_id],\n'
            '        rotation=0,\n'
            '        labelpad=75,\n'
            '        va="center",\n'
            '    )\n'
            '\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': '## 17 — Conditioning Experiment\n'
            '\n'
            'A single conditional diffusion model can learn several distributions.\n'
            '\n'
            'The key idea is to keep the **same initial Gaussian cloud** and change only $y$:\n'
            '\n'
            '$$\n'
            'p_\\theta(x\\mid y=0),\n'
            '\\;\n'
            'p_\\theta(x\\mid y=1),\n'
            '\\;\n'
            '\\ldots,\n'
            '\\;\n'
            'p_\\theta(x\\mid y=6).\n'
            '$$\n'
            '\n'
            'If the class embedding is doing its job, the same random starting configuration should be transformed '
            'into different geometric distributions.\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def generate_same_noise_for_all_classes(\n'
            '    n_points=700,\n'
            '    seed=2026,\n'
            '):\n'
            '    generator = torch.Generator(device=DEVICE)\n'
            '    generator.manual_seed(seed)\n'
            '\n'
            '    shared_noise = torch.randn(\n'
            '        n_points,\n'
            '        2,\n'
            '        generator=generator,\n'
            '        device=DEVICE,\n'
            '    )\n'
            '\n'
            '    outputs = {}\n'
            '\n'
            '    for class_id in range(NUM_CLASSES):\n'
            '        labels = torch.full(\n'
            '            (n_points,),\n'
            '            class_id,\n'
            '            dtype=torch.long,\n'
            '            device=DEVICE,\n'
            '        )\n'
            '\n'
            '        final_points, _ = sample(\n'
            '            model,\n'
            '            diffusion,\n'
            '            labels,\n'
            '            initial_noise=shared_noise,\n'
            '        )\n'
            '\n'
            '        outputs[class_id] = final_points.cpu()\n'
            '\n'
            '    return shared_noise.cpu(), outputs\n'
            '\n'
            '\n'
            'shared_noise, same_noise_outputs = generate_same_noise_for_all_classes()\n'},
 {'type': 'code',
  'source': 'fig, axes = plt.subplots(2, 4, figsize=(16, 8))\n'
            'axes = axes.ravel()\n'
            '\n'
            'for class_id in range(NUM_CLASSES):\n'
            '    points = same_noise_outputs[class_id].numpy()\n'
            '\n'
            '    axes[class_id].scatter(\n'
            '        points[:, 0],\n'
            '        points[:, 1],\n'
            '        s=7,\n'
            '        alpha=0.5,\n'
            '    )\n'
            '    axes[class_id].set_title(\n'
            '        f"Same noise → {PATTERN_NAMES[class_id]}"\n'
            '    )\n'
            '    axes[class_id].set_aspect("equal")\n'
            '    axes[class_id].set_xlim(-2.0, 2.0)\n'
            '    axes[class_id].set_ylim(-2.0, 2.0)\n'
            '\n'
            'axes[-1].axis("off")\n'
            'fig.suptitle("Changing Only the Conditioning Label")\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': '## 18 — Reconstruction / Denoising Experiment\n'
            '\n'
            'Now use real held-out test points.\n'
            '\n'
            'For a selected timestep $t$, construct\n'
            '\n'
            '$$\n'
            'x_t = q(x_t\\mid x_0),\n'
            '$$\n'
            '\n'
            'then use the network to estimate\n'
            '\n'
            '$$\n'
            '\\hat{x}_0.\n'
            '$$\n'
            '\n'
            'The point is to distinguish **generation from denoising**:\n'
            '\n'
            '- generation starts from Gaussian noise,\n'
            '- denoising starts from a real clean example and tries to recover it.\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def reconstruction_metrics(\n'
            '    class_id,\n'
            '    timestep=160,\n'
            '    points_per_class=700,\n'
            '):\n'
            '    class_points = test_points[test_labels == class_id]\n'
            '    points = class_points[:points_per_class]\n'
            '\n'
            '    x0 = torch.as_tensor(\n'
            '        points,\n'
            '        dtype=torch.float32,\n'
            '        device=DEVICE,\n'
            '    )\n'
            '    labels = torch.full(\n'
            '        (len(x0),),\n'
            '        class_id,\n'
            '        dtype=torch.long,\n'
            '        device=DEVICE,\n'
            '    )\n'
            '    t = torch.full(\n'
            '        (len(x0),),\n'
            '        timestep,\n'
            '        dtype=torch.long,\n'
            '        device=DEVICE,\n'
            '    )\n'
            '\n'
            '    noise = torch.randn_like(x0)\n'
            '    xt = q_sample(\n'
            '        x0,\n'
            '        t,\n'
            '        diffusion,\n'
            '        noise=noise,\n'
            '    )\n'
            '\n'
            '    eps_hat = model(\n'
            '        xt,\n'
            '        t,\n'
            '        labels,\n'
            '    )\n'
            '    x0_hat = predict_x0_from_noise(\n'
            '        xt,\n'
            '        t,\n'
            '        eps_hat,\n'
            '        diffusion,\n'
            '    )\n'
            '\n'
            '    mse = F.mse_loss(x0_hat, x0).item()\n'
            '\n'
            '    return (\n'
            '        x0.cpu(),\n'
            '        xt.cpu(),\n'
            '        x0_hat.cpu(),\n'
            '        mse,\n'
            '    )\n'
            '\n'
            '\n'
            'fig, axes = plt.subplots(\n'
            '    NUM_CLASSES,\n'
            '    3,\n'
            '    figsize=(11, 3.0 * NUM_CLASSES),\n'
            ')\n'
            '\n'
            'reconstruction_mses = {}\n'
            '\n'
            'for class_id in range(NUM_CLASSES):\n'
            '    x0_true, xt_obs, x0_pred, mse = reconstruction_metrics(\n'
            '        class_id,\n'
            '        timestep=160,\n'
            '    )\n'
            '    reconstruction_mses[class_id] = mse\n'
            '\n'
            '    clouds = [\n'
            '        x0_true.numpy(),\n'
            '        xt_obs.numpy(),\n'
            '        x0_pred.numpy(),\n'
            '    ]\n'
            '    titles = [\n'
            '        "Ground Truth",\n'
            '        "Noisy Observation",\n'
            '        f"Predicted x₀\\nMSE={mse:.4f}",\n'
            '    ]\n'
            '\n'
            '    for col in range(3):\n'
            '        axes[class_id, col].scatter(\n'
            '            clouds[col][:, 0],\n'
            '            clouds[col][:, 1],\n'
            '            s=6,\n'
            '            alpha=0.5,\n'
            '        )\n'
            '        axes[class_id, col].set_aspect("equal")\n'
            '        axes[class_id, col].set_xlim(-2.0, 2.0)\n'
            '        axes[class_id, col].set_ylim(-2.0, 2.0)\n'
            '\n'
            '        if class_id == 0:\n'
            '            axes[class_id, col].set_title(titles[col])\n'
            '\n'
            '    axes[class_id, 0].set_ylabel(\n'
            '        PATTERN_NAMES[class_id],\n'
            '        rotation=0,\n'
            '        labelpad=75,\n'
            '        va="center",\n'
            '    )\n'
            '\n'
            'plt.tight_layout()\n'
            'plt.show()\n'
            '\n'
            'print("Reconstruction MSE by class:")\n'
            'for class_id, mse in reconstruction_mses.items():\n'
            '    print(f"{class_id}: {mse:.6f} — {PATTERN_NAMES[class_id]}")\n'},
 {'type': 'markdown',
  'source': '## 19 — Quantitative Evaluation\n'
            '\n'
            'Two direct measurements are useful here.\n'
            '\n'
            '### 1. Noise prediction MSE\n'
            '\n'
            '$$\n'
            '\\frac{1}{N}\n'
            '\\sum_i\n'
            '\\left\\|\n'
            '\\epsilon_i-\\hat{\\epsilon}_i\n'
            '\\right\\|^2.\n'
            '$$\n'
            '\n'
            '### 2. Reconstruction MSE\n'
            '\n'
            '$$\n'
            '\\frac{1}{N}\n'
            '\\sum_i\n'
            '\\left\\|\n'
            'x_{0,i}-\\hat{x}_{0,i}\n'
            '\\right\\|^2.\n'
            '$$\n'
            '\n'
            'For **generated** clouds, pointwise MSE is not the right concept because generated points do not have a '
            'one-to-one correspondence with the test points.\n'
            '\n'
            'So we also compute an RBF-kernel MMD on random subsets. This compares distributions rather than matching '
            'points by index.\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def rbf_mmd(x, y, max_points=400):\n'
            '    x = x.float().to(DEVICE)\n'
            '    y = y.float().to(DEVICE)\n'
            '\n'
            '    if len(x) > max_points:\n'
            '        x = x[:max_points]\n'
            '    if len(y) > max_points:\n'
            '        y = y[:max_points]\n'
            '\n'
            '    xy = torch.cat([x, y], dim=0)\n'
            '\n'
            '    distances = torch.cdist(\n'
            '        xy,\n'
            '        xy,\n'
            '        p=2,\n'
            '    )\n'
            '    positive = distances[distances > 0]\n'
            '\n'
            '    bandwidth = torch.median(positive)\n'
            '    bandwidth = torch.clamp(\n'
            '        bandwidth,\n'
            '        min=torch.tensor(\n'
            '            1e-3,\n'
            '            device=DEVICE,\n'
            '        ),\n'
            '    )\n'
            '\n'
            '    def kernel(a, b):\n'
            '        dist2 = torch.cdist(a, b, p=2) ** 2\n'
            '        return torch.exp(\n'
            '            -dist2 / (2.0 * bandwidth ** 2)\n'
            '        )\n'
            '\n'
            '    k_xx = kernel(x, x).mean()\n'
            '    k_yy = kernel(y, y).mean()\n'
            '    k_xy = kernel(x, y).mean()\n'
            '\n'
            '    return (k_xx + k_yy - 2.0 * k_xy).item()\n'
            '\n'
            '\n'
            'noise_eval_values = []\n'
            'generated_mmd = {}\n'
            '\n'
            'for class_id in range(NUM_CLASSES):\n'
            '    class_mask = test_labels == class_id\n'
            '    real = torch.as_tensor(\n'
            '        test_points[class_mask][:900],\n'
            '        dtype=torch.float32,\n'
            '    )\n'
            '\n'
            '    generated = generated_by_class[class_id][:900]\n'
            '\n'
            '    generated_mmd[class_id] = rbf_mmd(\n'
            '        real,\n'
            '        generated,\n'
            '    )\n'
            '\n'
            'print("Noise prediction MSE:", eps_mse)\n'
            'print()\n'
            'print("Reconstruction MSE:")\n'
            'for class_id, value in reconstruction_mses.items():\n'
            '    print(f"  {PATTERN_NAMES[class_id]}: {value:.6f}")\n'
            '\n'
            'print()\n'
            'print("RBF-MMD between real test points and generated points:")\n'
            'for class_id, value in generated_mmd.items():\n'
            '    print(f"  {PATTERN_NAMES[class_id]}: {value:.6f}")\n'},
 {'type': 'markdown',
  'source': 'These measurements should be read carefully.\n'
            '\n'
            "A lower reconstruction MSE means the model's direct $\\hat{x}_0$ estimate is closer to the held-out clean "
            'points in Euclidean space.\n'
            '\n'
            'MMD is different: it asks whether the generated **distribution** resembles the real distribution under an '
            'RBF-kernel comparison.\n'
            '\n'
            'Neither metric by itself is a complete measure of visual generative quality.\n'},
 {'type': 'markdown',
  'source': '## 20 — Visual Failure Cases\n'
            '\n'
            'A useful diffusion notebook should show imperfect results too.\n'
            '\n'
            'The following cell identifies the three classes with the largest observed MMD in this run and places the '
            'generated distribution next to its ground truth. The interpretation is deliberately empirical: these are '
            'the largest discrepancies **in this experiment**, not a universal ranking of pattern difficulty.\n'},
 {'type': 'code',
  'source': 'largest_discrepancies = sorted(\n'
            '    generated_mmd.items(),\n'
            '    key=lambda item: item[1],\n'
            '    reverse=True,\n'
            ')[:3]\n'
            '\n'
            'fig, axes = plt.subplots(\n'
            '    len(largest_discrepancies),\n'
            '    2,\n'
            '    figsize=(9, 4 * len(largest_discrepancies)),\n'
            ')\n'
            '\n'
            'if len(largest_discrepancies) == 1:\n'
            '    axes = np.array([axes])\n'
            '\n'
            'for row, (class_id, mmd_value) in enumerate(largest_discrepancies):\n'
            '    real = test_points[test_labels == class_id][:800]\n'
            '    generated = generated_by_class[class_id].numpy()\n'
            '\n'
            '    axes[row, 0].scatter(\n'
            '        real[:, 0],\n'
            '        real[:, 1],\n'
            '        s=6,\n'
            '        alpha=0.5,\n'
            '    )\n'
            '    axes[row, 0].set_title(\n'
            '        f"Ground Truth — {PATTERN_NAMES[class_id]}"\n'
            '    )\n'
            '    axes[row, 0].set_aspect("equal")\n'
            '    axes[row, 0].set_xlim(-2.0, 2.0)\n'
            '    axes[row, 0].set_ylim(-2.0, 2.0)\n'
            '\n'
            '    axes[row, 1].scatter(\n'
            '        generated[:, 0],\n'
            '        generated[:, 1],\n'
            '        s=6,\n'
            '        alpha=0.5,\n'
            '    )\n'
            '    axes[row, 1].set_title(\n'
            '        f"Generated — MMD={mmd_value:.5f}"\n'
            '    )\n'
            '    axes[row, 1].set_aspect("equal")\n'
            '    axes[row, 1].set_xlim(-2.0, 2.0)\n'
            '    axes[row, 1].set_ylim(-2.0, 2.0)\n'
            '\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': 'Observed discrepancies can come from several concrete factors visible in the experiment, such as:\n'
            '\n'
            '- limited MLP capacity,\n'
            '- limited training time,\n'
            '- the complexity of the target geometry,\n'
            '- the chosen diffusion schedule,\n'
            '- overlap between local regions of different structures.\n'
            '\n'
            'These are hypotheses to inspect against the actual experiment rather than fixed explanations.\n'},
 {'type': 'markdown',
  'source': '## 21 — Optional Challenge: More Complex GPT Knot\n'
            '\n'
            'We can perturb the procedural knot without changing its overall family.\n'
            '\n'
            'This gives a simple out-of-distribution challenge: the network was trained on the original knot '
            'generator, while the new cloud has stronger deformation and rotational variation.\n'},
 {'type': 'code',
  'source': 'ood_rng = np.random.default_rng(2027)\n'
            '\n'
            'ood_knot = make_gpt_inspired_knot(\n'
            '    1400,\n'
            '    ood_rng,\n'
            '    loop_count=6,\n'
            '    deformation=0.10,\n'
            '    rotation_jitter=0.14,\n'
            '    coordinate_noise=0.035,\n'
            ')\n'
            '\n'
            '# Apply the same global normalization used by the original dataset.\n'
            'ood_knot = (\n'
            '    ood_knot\n'
            '    / np.max(np.abs(ood_knot))\n'
            '    * 1.78\n'
            ').astype(np.float32)\n'
            '\n'
            'fig, axes = plt.subplots(1, 2, figsize=(10, 4.5))\n'
            '\n'
            'axes[0].scatter(\n'
            '    test_points[test_labels == 6][:900, 0],\n'
            '    test_points[test_labels == 6][:900, 1],\n'
            '    s=6,\n'
            '    alpha=0.5,\n'
            ')\n'
            'axes[0].set_title("Training-family GPT-Inspired Knot")\n'
            'axes[0].set_aspect("equal")\n'
            'axes[0].set_xlim(-2.0, 2.0)\n'
            'axes[0].set_ylim(-2.0, 2.0)\n'
            '\n'
            'axes[1].scatter(\n'
            '    ood_knot[:, 0],\n'
            '    ood_knot[:, 1],\n'
            '    s=6,\n'
            '    alpha=0.5,\n'
            ')\n'
            'axes[1].set_title("More Difficult OOD Knot")\n'
            'axes[1].set_aspect("equal")\n'
            'axes[1].set_xlim(-2.0, 2.0)\n'
            'axes[1].set_ylim(-2.0, 2.0)\n'
            '\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'code',
  'source': '@torch.no_grad()\n'
            'def denoise_ood_knot(\n'
            '    points,\n'
            '    class_id=6,\n'
            '    timestep=180,\n'
            '):\n'
            '    x0 = torch.as_tensor(\n'
            '        points,\n'
            '        dtype=torch.float32,\n'
            '        device=DEVICE,\n'
            '    )\n'
            '    labels = torch.full(\n'
            '        (len(x0),),\n'
            '        class_id,\n'
            '        dtype=torch.long,\n'
            '        device=DEVICE,\n'
            '    )\n'
            '    t = torch.full(\n'
            '        (len(x0),),\n'
            '        timestep,\n'
            '        dtype=torch.long,\n'
            '        device=DEVICE,\n'
            '    )\n'
            '\n'
            '    noise = torch.randn_like(x0)\n'
            '    xt = q_sample(\n'
            '        x0,\n'
            '        t,\n'
            '        diffusion,\n'
            '        noise=noise,\n'
            '    )\n'
            '\n'
            '    eps_hat = model(\n'
            '        xt,\n'
            '        t,\n'
            '        labels,\n'
            '    )\n'
            '    x0_hat = predict_x0_from_noise(\n'
            '        xt,\n'
            '        t,\n'
            '        eps_hat,\n'
            '        diffusion,\n'
            '    )\n'
            '\n'
            '    return (\n'
            '        x0.cpu(),\n'
            '        xt.cpu(),\n'
            '        x0_hat.cpu(),\n'
            '        F.mse_loss(x0_hat, x0).item(),\n'
            '    )\n'
            '\n'
            '\n'
            'ood_true, ood_noisy, ood_pred, ood_mse = denoise_ood_knot(\n'
            '    ood_knot\n'
            ')\n'
            '\n'
            'fig, axes = plt.subplots(1, 3, figsize=(13, 4.5))\n'
            '\n'
            'for ax, points, title in zip(\n'
            '    axes,\n'
            '    [\n'
            '        ood_true.numpy(),\n'
            '        ood_noisy.numpy(),\n'
            '        ood_pred.numpy(),\n'
            '    ],\n'
            '    [\n'
            '        "OOD Ground Truth",\n'
            '        "OOD Noisy Observation",\n'
            '        f"OOD Predicted x₀\\nMSE={ood_mse:.5f}",\n'
            '    ],\n'
            '):\n'
            '    ax.scatter(\n'
            '        points[:, 0],\n'
            '        points[:, 1],\n'
            '        s=6,\n'
            '        alpha=0.5,\n'
            '    )\n'
            '    ax.set_title(title)\n'
            '    ax.set_aspect("equal")\n'
            '    ax.set_xlim(-2.0, 2.0)\n'
            '    ax.set_ylim(-2.0, 2.0)\n'
            '\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': '## 22 — Final Conceptual Connection\n'
            '\n'
            'Everything in the notebook reduces back to the same DDPM chain from Notebook 07.\n'
            '\n'
            '### Forward process\n'
            '\n'
            '$$\n'
            'x_t\n'
            '=\n'
            '\\sqrt{\\bar\\alpha_t}x_0\n'
            '+\n'
            '\\sqrt{1-\\bar\\alpha_t}\\epsilon.\n'
            '$$\n'
            '\n'
            '### Learned noise prediction\n'
            '\n'
            '$$\n'
            '\\epsilon_\\theta(x_t,t,y).\n'
            '$$\n'
            '\n'
            '### Clean-data estimate\n'
            '\n'
            '$$\n'
            '\\hat{x}_0\n'
            '=\n'
            '\\frac{\n'
            'x_t\n'
            '-\n'
            '\\sqrt{1-\\bar\\alpha_t}\n'
            '\\epsilon_\\theta(x_t,t,y)\n'
            '}{\n'
            '\\sqrt{\\bar\\alpha_t}\n'
            '}.\n'
            '$$\n'
            '\n'
            '### Reverse mean\n'
            '\n'
            '$$\n'
            '\\mu_\\theta(x_t,t,y)\n'
            '=\n'
            '\\frac{1}{\\sqrt{\\alpha_t}}\n'
            '\\left(\n'
            'x_t\n'
            '-\n'
            '\\frac{\\beta_t}{\\sqrt{1-\\bar\\alpha_t}}\n'
            '\\epsilon_\\theta(x_t,t,y)\n'
            '\\right).\n'
            '$$\n'
            '\n'
            '### Reverse transition\n'
            '\n'
            '$$\n'
            'x_{t-1}\n'
            '=\n'
            '\\mu_\\theta\n'
            '+\n'
            '\\sqrt{\\tilde\\beta_t}\\,z.\n'
            '$$\n'
            '\n'
            'So the complete conceptual chain is\n'
            '\n'
            '```text\n'
            'Learn Noise\n'
            '     ↓\n'
            'Infer x₀\n'
            '     ↓\n'
            'Compute Reverse Mean\n'
            '     ↓\n'
            'Sample x_{t-1}\n'
            '     ↓\n'
            'Repeat\n'
            '     ↓\n'
            'Generate Geometry\n'
            '```\n'},
 {'type': 'markdown',
  'source': '## 23 — Final Results Gallery\n'
            '\n'
            'The gallery compares the final generated distributions with held-out ground truth.\n'},
 {'type': 'code',
  'source': 'fig, axes = plt.subplots(\n'
            '    NUM_CLASSES,\n'
            '    2,\n'
            '    figsize=(10, 3.0 * NUM_CLASSES),\n'
            ')\n'
            '\n'
            'for class_id in range(NUM_CLASSES):\n'
            '    real = test_points[test_labels == class_id][:800]\n'
            '    generated = generated_by_class[class_id].numpy()\n'
            '\n'
            '    axes[class_id, 0].scatter(\n'
            '        real[:, 0],\n'
            '        real[:, 1],\n'
            '        s=6,\n'
            '        alpha=0.5,\n'
            '    )\n'
            '    axes[class_id, 0].set_title("Ground Truth")\n'
            '    axes[class_id, 0].set_aspect("equal")\n'
            '    axes[class_id, 0].set_xlim(-2.0, 2.0)\n'
            '    axes[class_id, 0].set_ylim(-2.0, 2.0)\n'
            '\n'
            '    axes[class_id, 1].scatter(\n'
            '        generated[:, 0],\n'
            '        generated[:, 1],\n'
            '        s=6,\n'
            '        alpha=0.5,\n'
            '    )\n'
            '    axes[class_id, 1].set_title(\n'
            '        f"Generated — {PATTERN_NAMES[class_id]}"\n'
            '    )\n'
            '    axes[class_id, 1].set_aspect("equal")\n'
            '    axes[class_id, 1].set_xlim(-2.0, 2.0)\n'
            '    axes[class_id, 1].set_ylim(-2.0, 2.0)\n'
            '\n'
            'plt.tight_layout()\n'
            'plt.show()\n'},
 {'type': 'markdown',
  'source': '## 24 — Final Takeaways\n'
            '\n'
            'The mathematical story is compact:\n'
            '\n'
            '$$\n'
            '\\boxed{\n'
            '\\text{Forward diffusion destroys geometry gradually.}\n'
            '}\n'
            '$$\n'
            '\n'
            '$$\n'
            '\\boxed{\n'
            '\\text{The network learns the noise hidden inside each noisy point.}\n'
            '}\n'
            '$$\n'
            '\n'
            '$$\n'
            '\\boxed{\n'
            '\\text{Noise prediction gives an estimate of the clean geometry.}\n'
            '}\n'
            '$$\n'
            '\n'
            '$$\n'
            '\\boxed{\n'
            '\\text{The reverse Gaussian step repeatedly reconstructs the distribution.}\n'
            '}\n'
            '$$\n'
            '\n'
            '$$\n'
            '\\boxed{\n'
            '\\text{Conditioning lets one DDPM learn multiple geometric distributions.}\n'
            '}\n'
            '$$\n'
            '\n'
            'The important result is not simply that the final scatter plot looks correct.\n'
            '\n'
            'The reverse trajectory demonstrates **how structured geometry emerges progressively from an initially '
            'unstructured Gaussian distribution**.\n'
            '\n'
            'Notebook 07 answered:\n'
            '\n'
            '> **How does DDPM work mathematically?**\n'
            '\n'
            'Notebook 08 answers:\n'
            '\n'
            '> **What does DDPM actually learn when the data distribution has visible geometric structure?**\n'},
 {'type': 'markdown',
  'source': '### Artifact checklist\n'
            '\n'
            'When the notebook has been executed, the `artifacts/` directory should contain:\n'
            '\n'
            '```text\n'
            'artifacts/\n'
            '    pattern_00_blob.gif\n'
            '    pattern_01_ring.gif\n'
            '    pattern_02_moons.gif\n'
            '    pattern_03_nested_rings.gif\n'
            '    pattern_04_spiral.gif\n'
            '    pattern_05_double_spiral.gif\n'
            '    pattern_06_gpt_knot.gif\n'
            '    all_patterns_reverse_diffusion.gif\n'
            '```\n'
            '\n'
            'The best model checkpoint is also saved as:\n'
            '\n'
            '```text\n'
            'artifacts/best_diffusion_2d.pt\n'
            '```\n'}]

def build_notebook():
    nb = nbf.v4.new_notebook()
    nb['metadata'] = {
        'kernelspec': {
            'display_name': 'Python 3',
            'language': 'python',
            'name': 'python3',
        },
        'language_info': {'name': 'python', 'pygments_lexer': 'ipython3'},
    }

    cells = []
    for spec in CELL_SPECS:
        if spec['type'] == 'markdown':
            cells.append(nbf.v4.new_markdown_cell(spec['source']))
        elif spec['type'] == 'code':
            cells.append(nbf.v4.new_code_cell(spec['source']))
        else:
            raise ValueError(f"Unknown cell type: {spec['type']}")

    nb['cells'] = cells
    return nb


def main():
    notebook = build_notebook()
    nbf.write(notebook, OUTPUT_NOTEBOOK)
    print(f'Wrote {OUTPUT_NOTEBOOK.resolve()}')
    print(f"Created {len(notebook['cells'])} notebook cells.")


if __name__ == '__main__':
    main()
